### ISSUE TITLE
How long does it take to train the model?

### ISSUE THREAD

**Issue by StarCycle** [bytedance/GR-1#2]
Hello @bdrhtw,

Thank you for making it open source!

What kind of GPU did you use to train this model? How many GPU hours did you use? I find that you used 8M frames from Ego4D but I am not sure about the actual training cost.

Best,
StarCycle

**Comment by bdrhtw** [comment]
Hi @StarCycle , we used 32 V100 to pretrain and finetune GR-1. Pretraining takes about 4 days; finetuning takes about 1 day.

**Comment by StarCycle** [comment]
Thank you for your response!

**Comment by StarCycle** [comment]
@bdrhtw Do you use V100 32G or V100 16G?

**Comment by bdrhtw** [comment]
We were using V100 32G.
